#!/usr/bin/env bash
source /home/vcdurra/OpenFOAM/OpenFOAM-v2012/etc/bashrc
# Parse arguments for library compilation without documentation by default
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake libso src
